config/routes.rb
Rails.application.routes.draw do

root 'posts1s#index', as: 'home'
#root 'posts#index', as: 'home'
#get 'pages#home'
get 'about' => 'pages#about', as: 'about'

resources :posts1s do
	resources :comms
end
devise_for :users
resources :posts do
	resources :comments
end

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comm.rb
class Comm < ApplicationRecord
  belongs_to :posts1
  	validates :body, presence: true
end

app/models/posts1.rb
class Posts1 < ApplicationRecord
  belongs_to :user
  has_many :comms, dependent: :destroy
	validates :title, presence: true, length: {minimum: 5}
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

def username
  return self.email.split('@')[0].capitalize
end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/comms_controller.rb
class CommsController < ApplicationController

def create
@posts1 = Posts1.find(params[:posts1_id])
@comm = @posts1.comms.create(comm_params)
redirect_to posts1_path(@posts1)
end

private def comm_params
  params.require(:comm).permit(:username, :body)
end

end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
	def about
		@heading = 'Page is about us!'
		@text = 'На створення нашого проекту нас надихнула соціальна мережа Twitter. У вік цифрових технологій спілкування в інтернеті є невід‘ємною частиною життя сучасної людини,  тому так важливо знайти місце, де б ти міг поділитися своїми думками і обмінятись інформацією з іншими користувачами.
Наша ідея - це соціальна мережа для комунікації між студентами Києво-Монилянської академії, адже спілкування не тільки у межах університету, але й у віртуальному житті, зробить нашу спільноту ще більш згуртованою. Вона допоможе завжди бути на зв‘язку, ділитися важливою та цікавою інформацією з колегами та просто дізнатися щось нове про студентів нашої академії.'
	end
end

app/controllers/posts1s_controller.rb
class Posts1sController < ApplicationController
  before_action :set_posts1, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, except: [:show, :index]

  # GET /posts1s
  # GET /posts1s.json
  def index
    @posts1s = Posts1.all
  end

  # GET /posts1s/1
  # GET /posts1s/1.json
  def show
  end

  # GET /posts1s/new
  def new
    @posts1 = Posts1.new
  end

  # GET /posts1s/1/edit
  def edit
  end

  # POST /posts1s
  # POST /posts1s.json
  def create
    @posts1 = Posts1.new(posts1_params)
    @posts1.user = current_user
    respond_to do |format|
      if @posts1.save
        format.html { redirect_to @posts1, notice: 'Post was successfully created.' }
        format.json { render :show, status: :created, location: @posts1 }
      else
        format.html { render :new }
        format.json { render json: @posts1.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /posts1s/1
  # PATCH/PUT /posts1s/1.json
  def update
    respond_to do |format|
      if @posts1.update(posts1_params)
        format.html { redirect_to @posts1, notice: 'Post was successfully updated.' }
        format.json { render :show, status: :ok, location: @posts1 }
      else
        format.html { render :edit }
        format.json { render json: @posts1.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts1s/1
  # DELETE /posts1s/1.json
  def destroy
    @posts1.destroy
    respond_to do |format|
      format.html { redirect_to posts1s_url, notice: 'Post was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_posts1
      @posts1 = Posts1.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def posts1_params
      params.require(:posts1).permit(:title, :body, :user_id)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/comms_helper.rb
module CommsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/posts1s_helper.rb
module Posts1sHelper
end

app/views/layouts/_alerts.html.erb
<p class="notice"><%= notice %></p>
<p class="alert"><%= alert %></p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>BlogProject</title>
  <%= csrf_meta_tags %>

  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  <%= stylesheet_link_tag    'https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css'%>

  <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
</head>

<body>
  <div class="d-flex flex-column flex-md-row align-items-center p-3 px-md-4 mb-3 bg-white border-bottom shadow-sm">
    <h5 class="my-0 mr-md-auto font-weight-bold"><%= link_to "KMAtter",home_path %></h5>
    <nav class="my-2 my-md-0 mr-md-3">
      <span class="p-2 text-dark rounded card-header"><%= link_to "Main Page",home_path %></span>
      <span class="p-2 text-dark rounded card-header"><%= link_to "About Us",about_path %> </span>
    </nav>
  </div>
  <section class="navbar navbar-expand-lg navbar-light bg-light">
    <% if current_user %>
    <span class="p-2 text-dark"><%= link_to "Add Post",new_posts1_path %> </span>
    <%= link_to 'Sign out', destroy_user_session_path, method: :delete %>
    <% else %>
    <span class="p-2 text-dark"><%= link_to 'Sign up', new_user_registration_path %> </span>
    <span class="p-2 text-dark"> <%= link_to 'Sign in', new_user_session_path %></span>
    <% end %>

  </section>
  <div class="container">
    <%= render 'layouts/alerts' %>
    <%= yield %>
  </div>
</body>
</html>

app/views/pages/about.html.erb
<h4><%= @heading %></h4>
<p><%= @text %></p>

app/views/pages/home.html.erb
<h1>Pages#home</h1>
<p>Find me in app/views/pages/home.html.erb</p>

app/views/posts1s/_form.html.erb
<%= form_with(model: posts1, local: true) do |form| %>
  <% if posts1.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(posts1.errors.count, "error") %> prohibited this post from being saved:</h2>

      <ul>
      <% posts1.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field(:title, id: :posts1_title, :class => 'form-control') %>
  </div>

  <div class="field">
    <%= form.label :body %>
    <%= form.text_area(:body, id: :posts1_body, :class => 'form-control') %>
  </div>

  <div class="actions">
    <%= form.submit(:class => 'btn btn-success', :value => "Create") %>
  </div>
<% end %>

app/views/posts1s/edit.html.erb
<h1>Edit Post</h1>

<%= render 'form', posts1: @posts1 %>

<%= link_to 'Show', @posts1 %> |
<%= link_to 'Back', posts1s_path %>

app/views/posts1s/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Posts</h1>
<tbody>
  <% @posts1s.each do |posts1| %>

  <div class = "alert alert-light">
    <h3><%= posts1.title %></h3>
    <p> <%= posts1.body %></p>
    <strong><p><%= posts1.user.username %></p></strong>
    <%= link_to "Read more", posts1, :class => 'btn btn-outline-primary' %>
    <% if current_user && (current_user.admin | (posts1.user.username==current_user.username)) %>
    <%= link_to 'Edit', edit_posts1_path(posts1),:class => 'btn btn-outline-primary' %>
    <%= link_to 'Delete', posts1, method: :delete, data: { confirm: 'Are you sure?' },:class => 'btn btn-outline-primary' %>
    <% end %>
  </div>
  <% end %>
</tbody>
</table>

<br>

app/views/posts1s/new.html.erb
<h1>Add Post</h1>


<%= render 'form', posts1: @posts1 %>

<%= link_to 'Back', posts1s_path %>

app/views/posts1s/show.html.erb
<p>
  <strong>Title:</strong>
  <%= @posts1.title %>
</p>

<p>
  <strong>Body:</strong>
  <%= @posts1.body %>
</p>

<p>
  <strong>User:</strong>
  <%= @posts1.user.username %>
</p>
<% if current_user && (current_user.admin | (@posts1.user.username==current_user.username)) %>
<%= link_to 'Edit', edit_posts1_path(@posts1), :class => 'btn btn-warning' %> |
<%= link_to 'Delete', @posts1, method: :delete, data: { confirm: 'Are you sure?' }, :class => 'btn btn-danger' %> |
<% end %>
<%= link_to 'Back', posts1s_path, :class => 'btn btn-primary' %>
<hr>

<h2>All Comments</h2>
<% @posts1.comms.each do |comm| %>
<div class = "alert alert-light">
<p><strong><%= comm.username %> </strong> : <%= comm.body %></p>
</div>
<% end %>

<hr>

<%= form_for ([@posts1, @posts1.comms.build ]) do |f| %>
<% if current_user %>
<h2>Add Comments</h2>
    <%= f.text_field :username, required: true,  class: 'form-control', value:current_user.username, readonly: true %>
		<p>
		Comment Text<br>
		<%= f.text_area(:body, {:class => 'form-control'}) %>
	</p>
		<p>
		<%= f.submit("Add Comment", {:class => 'btn btn-warning'}) %>
	</p>
<% end %>
	<% end %>